### ISSUE TITLE
mirror data to S3

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub#12]

**Comment by bsweger** [comment]
Exciting! A few questions/clarifications?

1. What data you want to mirror to S3? Are there specific folders from the repo?
2. Should the mirrored data retain the same directory structure as the repo, or did you want to re-arrange it?
3. Am assuming that you want the S3 version to update when changes are merged to the repo's main branch; let me know if that's not the case!
4. Who should access to the S3 data? Do you want it publicly-accessible?

**Comment by elray1** [comment]
1. I think that in order for the data to be fully usable, we'd need the following folders: auxiliary-data, hub-config, model-metadata, model-output, target-data
2. I think it's probably easiest if it retains the same directory structure??
3. sounds good
4. yes, publicly-accessible would be great!

**Comment by bsweger** [comment]
Thanks, that all sounds good!

I forgot to ask--does/should the Hubverse have its own AWS account to keep billing and funds separate from Reich Lab projects?

Alternately, what we could do to get started is"tag" the Hubverse resources in the Reich Lab's account so we split those costs out if we need to.

**Comment by nickreich** [comment]
We only have the one ReichLab AWS account, no hubverse specific thing yet. It probably makes sense to have it as a separate thing in AWS. Would that require another email? or should we set up a separate account? Are there advantages to having them be together but tagged separately? (e.g. if we get accepted to the the AWS open data program?)

**Comment by nickreich** [comment]
I also think that for now, it would be fine to just roll with putting it all on ReichLab resources.

**Comment by bsweger** [comment]
Sure, we can start by using Reich Lab's AWS account, and I'll add a "hubverse" tag to this S3 bucket. Agree, that's much faster and more straightforward than setting up a new account.

To answer your prior questions:

- Each AWS account needs a distinct e-mail, but we could probably use the + alias to circumvent that (e.g.., nick@umass.edu and nick+hubverse@umass.edu are essentially the same address)
- Having a separate AWS account is the cleaner way to separate the concerns and would also allow us to, for example, add admins from outside Reich Lab without giving them access to resources for internal lab projects
- The tradeoff to separate accounts is more management/administration and also an added layer of complexity if we want resources in one account to interact with resources in another account 
- Am still a bit unclear how the open data program works, but my guess is that we'd have to apply once for each account
