### ISSUE TITLE
Update URL in model-metadata-schema.json?

### ISSUE THREAD

**Issue by bsweger** [Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub#21]
The `description` field in this repo's `model-metadata-schema.json` points to a URL from the [cdcepi GitHub organization](https://github.com/cdcepi/FluSight-forecast-hub/blob/main/model-metadata/README.md).

Is there a plan (or should we make a plan) to pull that info from the cdcepi README into hubDocs? Or at least into a place owned/controlled by the Hubverse?

In addition to ensuring that we can iterate on model-metadata documentation in a place that we control, there's a (maybe?) related unwanted behavior in hubDocs that we might be able to fix.

To see the unexpected behavior, go to https://hubdocs.readthedocs.io/en/latest/user-guide/model-metadata.html#template-metadata-schema-file and click the link after "please refer to"

If "please refer to" can link to somewhere in hubDocs instead of to GitHub, the "can't embed content from links to other domains" issue might go away.

This isn't urgent...for context, this secondary, possibly related issue came up in a [recent PR review](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/91#discussion_r1514934311)

**Comment by elray1** [comment]
Yes, thanks! I think that we should copy the model metadata description from flusight over to this repo and update that link to point to the file in this repo.
