### ISSUE TITLE
add sample output_type example data

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub#8]
would be nice to have `output_type = "sample"` in the model output files.  Perhaps we can set this up to have trajectories for one model and samples that are not trajectories for another model?

Involves the following tasks:

- [ ] update hub config files
- [ ] add model outputs
- [ ] add target values if necessary?

**Comment by elray1** [comment]
I have a question about logistics for how to do this. We have pretty well scoped out what the format of samples will be in [this thread](https://github.com/Infectious-Disease-Modeling-Hubs/schemas/issues/48), but support for samples does not yet exist in the hubverse schemas or hubValidations. Does it make sense to:

1. Be bold! Go ahead with setup of samples in the schema and model outputs
2. Act, but with caution. Do 1, but on a branch of this repository. Hold off on merging in until there is support for samples in core hubverse packages.
3. Wait until hubverse functionality exists. It won't be long anyways.

One deciding factor might be whether we want to prioritize getting these samples into a data set in `hubExamples`, or if they might be helpful to have in place when developing other hubverse functionality.

**Comment by annakrystalli** [comment]
I feel after the schema, working on some example data is the next important step to pushing functionality forward. 

I think working in a branch initially is probably sensible but I don't feel we'll need to wait for full functionality to release it.

**Comment by annakrystalli** [comment]
FYI I have the schema implemented as WIP (as I am testing some downstream implications before settling) here: https://github.com/Infectious-Disease-Modeling-Hubs/schemas/pull/71

**Comment by elray1** [comment]
There are two relevant scripts that could be updated to create model output data and target data:

- https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub/blob/main/internal-data-raw/create_model_output_data.R
- https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub/blob/main/internal-data-raw/create_target_data.R

There is an example of how to create samples independently for each target location/week [here](https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub/blob/e2e10d299ff2c916be970b024a02dfafbd543ece/internal-data-raw/create_model_output_data.R#L25-L41).

I think it would be nice to have a couple of examples of samples for models with one or two different compound forecast units that they're targeting:

- maybe one model with location and reference_date (i.e. forecast trajectories).  To be "statistically sound", you'd want these to be correlated across time within each location and reference_date combination.
- maybe another model with compound forecast unit based on all of location, reference_date, and target_end_date (and/or horizon).  These would be the default kinds of samples you'd get out of generating samples separately for each location/target date.
